<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Hanuman" failures="1" tests="2" name="Test" time="18.809" errors="0" timestamp="2025-06-22T22:42:04 IST">
  <testcase classname="TestClasses.TCLoginToAmazon" name="login" time="13.096"/>
  <testcase classname="TestClasses.TCLoginToAmazon" name="Failtestcase" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [2]
at TestClasses.TCLoginToAmazon.Failtestcase(TCLoginToAmazon.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- Failtestcase -->
</testsuite> <!-- Test -->
